"""Chat schema — request body for the POST /chat streaming endpoint."""

from typing import Literal, Optional

from pydantic import BaseModel, Field

from app.schemas.retrieval import RetrievedChunk
from app.services.cost_tracker import CostBreakdown
from app.services.embeddings import DEFAULT_EMBEDDING_MODEL


class ChatRequest(BaseModel):
    """Request body for the chat endpoint.

    The client specifies which LLM provider and model to use.
    The adapter pattern handles the rest behind the scenes.
    """

    # The user's question or message.
    query: str = Field(..., min_length=1, description="The user's message or question")

    # Which LLM provider to use — determines which adapter handles the request.
    provider: Literal["openai", "claude"] = Field(
        default="openai",
        description="LLM provider to use ('openai' or 'claude')",
    )

    # The specific model name to use (defaults differ per provider).
    model: Optional[str] = Field(
        default=None,
        description="Model name override (e.g. 'gpt-5.6-terra', 'claude-sonnet-5-latest')",
    )

    # Optional system prompt to steer the LLM's behaviour.
    system_prompt: Optional[str] = Field(
        default=None,
        description="Optional system prompt to guide LLM behaviour",
    )

    # Sampling temperature for the LLM.
    temperature: float = Field(
        default=0.3,
        ge=0.0,
        le=2.0,
        description="Sampling temperature (0 = deterministic, higher = creative)",
    )

    # Optional context chunks from the retrieval phase.
    # When supplied, the endpoint skips its own retrieval and uses these as-is.
    context_chunks: list[RetrievedChunk] = Field(
        default_factory=list,
        description=(
            "Pre-retrieved context chunks. If non-empty, the endpoint skips "
            "its own retrieval step and uses these instead."
        ),
    )

    # --- Retrieval (RAG) controls -------------------------------------------

    # Whether the endpoint should run retrieval before generation.
    use_rag: bool = Field(
        default=True,
        description="Run vector retrieval before generation (ignored if context_chunks is set)",
    )

    # How many chunks to pull from the vector store.
    top_k: int = Field(
        default=5,
        ge=1,
        le=50,
        description="Number of chunks to retrieve from the vector store",
    )

    # Minimum similarity score required for a chunk to be used.
    score_threshold: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Drop retrieved chunks scoring below this value",
    )

    # Embedding model used for the query — must match the stored vectors'.
    embedding_model: str = Field(
        default=DEFAULT_EMBEDDING_MODEL,
        description="Embedding model used to embed the query for retrieval",
    )


class ChatStreamMessageEvent(BaseModel):
    """Represents a standard text chunk event in the SSE stream.
    
    In SSE, this is typically sent as an unnamed event (implicitly 'message') 
    with the text delta in the data field.
    """
    data: str = Field(..., description="A chunk of text generated by the LLM")


class RetrievalEventData(BaseModel):
    """Payload of the `retrieval` SSE event.

    Sent once, before any text deltas, so the client can render citations
    and similarity scores while the answer is still streaming.
    """

    # Echo of the query that was embedded and searched.
    query: str = Field(..., description="The query used for the vector search")

    # Matched chunks, best score first, each carrying its similarity score.
    chunks: list[RetrievedChunk] = Field(
        default_factory=list,
        description="Retrieved chunks with similarity scores, best match first",
    )

    # How many candidates the vector store returned before filtering.
    total_searched: int = Field(
        default=0, ge=0, description="Number of candidate matches returned by the store"
    )

    # Embedding model used for the query.
    embedding_model: str = Field(default="", description="Model used to embed the query")


class ChatStreamRetrievalEvent(BaseModel):
    """Represents the retrieval event in the SSE stream.

    Sent at the start of the stream with the event name 'retrieval'.
    """

    event: Literal["retrieval"] = Field(default="retrieval", description="The SSE event name")
    data: RetrievalEventData = Field(..., description="Retrieved chunks and their scores")


class ErrorEventData(BaseModel):
    """Payload of the `error` SSE event.

    Emitted for a non-fatal failure in one pipeline stage; the stream
    continues afterwards in a degraded form.
    """

    # Which pipeline stage failed (e.g. "retrieval").
    stage: str = Field(..., description="Pipeline stage that failed")

    # Human-readable failure detail.
    message: str = Field(..., description="Description of the failure")


class ChatStreamErrorEvent(BaseModel):
    """Represents a non-fatal error event in the SSE stream.

    Sent with the event name 'error'; the stream is not terminated.
    """

    event: Literal["error"] = Field(default="error", description="The SSE event name")
    data: ErrorEventData = Field(..., description="Which stage failed, and why")


class ChatStreamUsageEvent(BaseModel):
    """Represents the final usage and cost event in the SSE stream.
    
    Sent at the very end of the stream with the event name 'usage'.
    """
    event: Literal["usage"] = Field(default="usage", description="The SSE event name")
    data: CostBreakdown = Field(..., description="Token usage and calculated cost breakdown")

